version: '3.3'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: fluxpay
    environment:
      - POSTGRES_DB=fluxpay
      - POSTGRES_USER=fluxpay-usr
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'