spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        globally_quoted_identifiers: 'true'
  datasource:
    hikari:
      maxLifeTime: '30000'
      connectionTimeout: '30000'
    url: jdbc:postgresql://localhost:5432/fluxpay
    username: fluxpay-usr
    password: postgres
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: payment-consumer
      auto-offset-reset: latest

  springdoc:
    api-docs:
      path: /api-docs
